version: '3'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "secret_password"
      MYSQL_DATABASE: reddit
    ports:
      - '3306:3306'
    volumes:
      - './init/_sql/:/docker-entrypoint-initdb.d/'

  mongodb:
    image: 'mongo:5'
    environment:
      - MONGO_INITDB_DATABASE=reddit
    ports:
      - '27017-27019:27017-27019'
